apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exampleapp-prod
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml
images:
  - name: nginx
    newTag: latest
