apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop
  namespace: argocd
spec:
  project: platform-prod
  source:
    path: apps/online-shop/overlays/prod
  destination:
    namespace: onlineshop-prod
