apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webapp
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml
images:
  - name: nginx
    newTag: "466de7e484b73b09256ee6501ed22b8d1398ffa5"
